name: Periodic health check

on:
  schedule:
  - cron: '40 16,5 * * *'

jobs:
  health_check_job:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3
      with:        
        url: https://jk-full-stack-pokedex.fly.dev
        max-attempts: 3
        retry-delay: 5s